[tool.poetry]
name = "pySigma-pipeline-ocsf"
version = "0.1.1"
description = "pySigma OCSF pipeline"
readme = "README.md"
authors = ["Hendrik Baecker <hb@process-zero.de>"]
license = "MIT"
repository = "https://github.com/SigmaHQ/pySigma-pipeline-ocsf"
packages = [
    { include = "sigma" }
]

[tool.poetry.dependencies]
python = ">=3.9,<4.0"
pysigma = "^0.11.23"

[tool.poetry.group.dev.dependencies]
defusedxml = "^0.7.1"
pytest = ">=7.3,<9.0"
pytest-cov = ">=4,<7"

[build-system]
requires = ["poetry-core>=1.8.1"]
build-backend = "poetry.core.masonry.api"
